---
- name: Reload service daemon
  ansible.builtin.shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable vagrant-k8s-cluster.service

- name: Run vagrant
  ansible.builtin.service:
    name: vagrant-k8s-cluster
    state: restarted
