image: python:3.10

ci:
  stage: build
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install ansible
    - pip install "ansible-lint[yamllint]"
  script:
    - ansible-playbook --syntax-check playbooks/*.yml
