---
- name: Install Vagrant for Debian systems
  when: ansible_os_family == "Debian"
  block:
    - name: Add HashiCorp apt signing key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Add hashicorp apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ubuntu_version_name }} main
        state: present
        filename: hashicorp.list
      changed_when: false
    - name: Install vagrant
      ansible.builtin.apt:
        name: vagrant
        state: present
        update_cache: true
