---
# Tasks file for vagrant role
# Reference: https://www.vagrantup.com/downloads

- name: Install Vagrant for Debian systems
  block:
    - name: Add HashiCorp apt signing key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Add VirtualBox public key
      apt_key:
        url: "{{ virtualbox_apt_key }}"
    - name: Add VirtualBox apt repository
      apt_repository:
        repo: "{{ virtualbox_apt_repo }}"
      changed_when: false
    - name: Install VirtualBox
      apt:
        name: "{{ virtualbox_name_debian }}"
        state: present
  when: ansible_os_family == "Debian"
