---
- name: Uninstall Vagrant for Debian systems
  when: ansible_os_family == "Debian"
  block:
    - name: Remove HashiCorp apt signing key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: absent
    - name: Remove hashicorp apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ubuntu_version_name }} main
        state: absent
        filename: hashicorp.list
      changed_when: false
    - name: Uninstall vagrant
      ansible.builtin.apt:
        name: vagrant
        state: absent
        update_cache: true
