---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

- name: Remove swapfile from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    # no bionic release (see https://packages.cloud.google.com/apt/dists)
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Configure node ip
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ kubernetes_controlnode_ip }}
    create: true
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart kubelet

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
