---
- name: Install Docker engine on Debian systems
  when: ansible_os_family == "Debian"
  block:
    - name: Add an apt signing key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add apt repository for stable version
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version_name }} stable
        state: present
        filename: docker.list
    - name: Install docker and its dependencies
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - Start docker
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ provisioning_username }}"
        group: docker
    - name: Change docker cgroup
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: docker_daemon_file
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
      when: docker_daemon_file.changed
