---
# Tasks file for docker_engine role

- name: Install Docker engine on Debian systems
  block:
    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version_name }} stable
        state: present
        filename: docker.list
    - name: Install docker and its dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - Start docker
    - name: Add user to docker group
      user:
        name: "{{ provisioning_username }}"
        group: docker
    - name: Change docker cgroup
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"]
          }
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: docker_daemon_file
    - name: Restart docker
      service:
        name: docker
        state: restarted
      when: docker_daemon_file.changed
  when: ansible_os_family == "Debian"
