---
# https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart

- name: Download calico operator manifest
  become: false
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/tigera-operator.yaml
    dest: ./calico-operator.yaml
    owner: "{{ ansible_user }}"
    group: "docker"
    mode: "0644"

- name: Install calico operator
  become: false
  kubernetes.core.k8s:
    state: present
    src: ./calico-operator.yaml

- name: Download calico resources manifest
  become: false
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/custom-resources.yaml
    dest: ./calico-resources.yaml
    owner: "{{ ansible_user }}"
    group: "docker"
    mode: "0644"

- name: Install calico resources
  become: false
  kubernetes.core.k8s:
    state: present
    src: ./calico-resources.yaml
