---
# Tasks file for virtualbox role
# Reference: https://www.virtualbox.org/wiki/Linux_Downloads

- name: Uninstall VirtualBox for Debian systems
  block:
    - name: Remove virtualbox public key
      apt_key:
        url: "{{ item }}"
        state: absent
      with_items:
        - https://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
        - https://www.virtualbox.org/download/oracle_vbox_2016.asc
        - https://www.virtualbox.org/download/oracle_vbox.asc
        - https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc
    - name: Remove virtualbox apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ubuntu_version_name }} contrib
        state: absent
        filename: virtualbox.list
    - name: Uninstall virtualbox
      apt:
        name: virtualbox-{{ virtualbox_version }}
        state: absent
  when: ansible_os_family == "Debian"
