---
- name: Uninstall VirtualBox for Debian systems
  when: ansible_os_family == "Debian"
  block:
    - name: Remove virtualbox public key
      ansible.builtin.apt_key:
        url: "{{ item }}"
        state: absent
      with_items:
        - https://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
        - https://www.virtualbox.org/download/oracle_vbox_2016.asc
        - https://www.virtualbox.org/download/oracle_vbox.asc
        - https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc
    - name: Remove virtualbox apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ubuntu_version_name }} contrib
        state: absent
        filename: virtualbox.list
    - name: Uninstall virtualbox
      ansible.builtin.apt:
        name: virtualbox-{{ virtualbox_version }}
        state: absent
