---
- name: Run kubelet installation
  ansible.builtin.include_role:
    name: kubernetes_common
    tasks_from: kubelet

- name: Copy the join command to server location
  ansible.builtin.copy:
    src: ./join-command.sh
    dest: /tmp/join-command.sh
    owner: root
    group: root
    mode: "0777"

- name: Join the node to cluster
  ansible.builtin.command:
    cmd: sh /tmp/join-command.sh
    creates: "/etc/kubernetes/kubelet.conf"
