---
- name: Check if kubelet.conf exists
  ansible.builtin.stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- name: Join to cluster if needed
  ansible.builtin.include_tasks: join.yml
  when: not kubelet_conf.stat.exists
