---
- name: Install required components for Debian systems
  when: ansible_os_family == "Debian"
  block:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true
    - name: Install Debian packages required for installation over HTTPS
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - gpg-agent
