---

# sudo systemctl start containerd
- name: Start containerd
  ansible.builtin.service:
    name: containerd
    state: started

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Reload sysctl
  ansible.builtin.command:
    cmd:
      sysctl --system
