---
- name: Install Kubernetes control plane
  hosts: all
  become: true
  roles:
    - ../roles/linux_server
    # - ../roles/docker_engine
    - ../roles/containerd
    - ../roles/kubernetes_controlplane
